{
 "title": "Proxy Metrics",
 "description": "Proxy Metrics",
 "tags": [ "proxy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "pulsar_proxy_active_connections{container=~\".+\", job=~\".*proxy\"}"
   },
   {
    "name": "instance",
    "label": "Proxy",
    "query": "pulsar_proxy_active_connections{pod=~\".+\", job=~\".*proxy\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_proxy_active_connections{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "New connections (conn / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_new_connections{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[30s])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Rejected connections (conn / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_connections{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[30s])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_binary_ops{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Traffic - bytes per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_binary_ops{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP  reqs per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_requests_total{container=~\"$cluster\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Topic lookups per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_lookup_requests{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GetPartitionsMetadata per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_partitions_metadata_requests{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GetNamespaceTopics per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_get_topics_of_namespace_requests{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Lookups rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_lookup_requests{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Partitions requests rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_partitions_metadata_requests{container=~\"$cluster\", job=~\".*proxy\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GetNamespaceTopics requests rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    pulsar_proxy_rejected_get_topics_of_namespace_requests{\n            container=~\"$cluster\", job=~\".*proxy\", \n            pod=~\"$instance\"}[1m]\n    )\n  ) \nby (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}